model:
  name: DeepLabV3Plus
  encoder: resnet18
  weights: imagenet  # use pretrained encoder weights
  normalize: false   # data already normalised to [0,1] - skip imagenet mean/std normalisation
  channels: 3
  classes: 20

training:
  optimizer:
    type: adam
    lr: 0.0001
  scheduler:
    steps: [20, 35]
    factor: 0.1
  loss: dice
  epochs: 50
  batch_size: 8

data:
  train:
    - C:/Cloud/OneDrive/13_Projects/140_Smaller_Projects/1411_NHR/2_Tiles/250cm/HT/train
    - C:/Cloud/OneDrive/13_Projects/140_Smaller_Projects/1411_NHR/2_Tiles/250cm/KT/train
    - C:/Cloud/OneDrive/13_Projects/140_Smaller_Projects/1411_NHR/2_Tiles/250cm/MT/train
  valid:
    - C:/Cloud/OneDrive/13_Projects/140_Smaller_Projects/1411_NHR/2_Tiles/250cm/HT/valid
    - C:/Cloud/OneDrive/13_Projects/140_Smaller_Projects/1411_NHR/2_Tiles/250cm/KT/valid
    - C:/Cloud/OneDrive/13_Projects/140_Smaller_Projects/1411_NHR/2_Tiles/250cm/MT/valid
  out: C:/Cloud/OneDrive/13_Projects/140_Smaller_Projects/1411_NHR/3_Test_Run/run_03
